### ISSUE TITLE
[BUG]: DFP `fetch_example_data.py` broken on `s3fs=2023.6.0`

### ISSUE THREAD

**Issue by mdemoret-nv** [nv-morpheus/Morpheus#1047]
### Version

23.07

### Which installation method(s) does this occur on?

Docker, Conda, Source

### Describe the bug.

With the upgrade to `s3fs=2023.6.0` in PR #1023, we solved one problem but caused another. Now the `examples/digital_fingerprinting/fetch_example_data.py` fails.

We need to determine how to best download the files with the most recent version of s3fs

### Minimum reproducible example

```shell
Ensure s3fs=2023.6 is installed

`python examples/digital_fingerprinting/fetch_example_data.py all`
```

### Relevant log output

```shell
python examples/digital_fingerprinting/fetch_example_data.py all
Downloading DUO_2022-08-01T00_05_06.806Z.json
Traceback (most recent call last):
  File "<CONDA_ENV>/lib/python3.10/site-packages/s3fs/core.py", line 693, in _lsdir
    async for c in self._iterdir(
  File "<CONDA_ENV>/lib/python3.10/site-packages/s3fs/core.py", line 743, in _iterdir
    async for i in it:
  File "<CONDA_ENV>/lib/python3.10/site-packages/aiobotocore/paginate.py", line 30, in __anext__
    response = await self._make_request(current_kwargs)
  File "<CONDA_ENV>/lib/python3.10/site-packages/aiobotocore/client.py", line 371, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<MORPHEUS_ROOT>/examples/digital_fingerprinting/fetch_example_data.py", line 588, in <module>
    main()
  File "<MORPHEUS_ROOT>/examples/digital_fingerprinting/fetch_example_data.py", line 584, in main
    fetch_dataset(ds)
  File "<MORPHEUS_ROOT>/examples/digital_fingerprinting/fetch_example_data.py", line 554, in fetch_dataset
    fs.get(S3_BASE_PATH + f, train_dir + f)
  File "<CONDA_ENV>/lib/python3.10/site-packages/fsspec/asyn.py", line 121, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "<CONDA_ENV>/lib/python3.10/site-packages/fsspec/asyn.py", line 106, in sync
    raise return_result
  File "<CONDA_ENV>/lib/python3.10/site-packages/fsspec/asyn.py", line 61, in _runner
    result[0] = await coro
  File "<CONDA_ENV>/lib/python3.10/site-packages/fsspec/asyn.py", line 579, in _get
    rpaths = [
  File "<CONDA_ENV>/lib/python3.10/site-packages/fsspec/asyn.py", line 580, in <listcomp>
    p for p in rpaths if not (trailing_sep(p) or await self._isdir(p))
  File "<CONDA_ENV>/lib/python3.10/site-packages/s3fs/core.py", line 1380, in _isdir
    return bool(await self._lsdir(path))
  File "<CONDA_ENV>/lib/python3.10/site-packages/s3fs/core.py", line 706, in _lsdir
    raise translate_boto_error(e)
PermissionError: Access Denied
```

### Full env printout

```shell
Fixing this requires running `mamba install s3fs=2022.8.2` which shows the broken env -> working env

  - aiobotocore     2.5.0  pyhd8ed1ab_0  conda-forge                  
  + aiobotocore     2.4.0  pyhd8ed1ab_0  conda-forge/noarch     Cached
  - boto3         1.26.76  pyhd8ed1ab_0  conda-forge                  
  + boto3         1.24.59  pyhd8ed1ab_0  conda-forge/noarch     Cached
  - botocore      1.29.76  pyhd8ed1ab_0  conda-forge                  
  + botocore      1.27.59  pyhd8ed1ab_0  conda-forge/noarch     Cached
  - fsspec       2023.6.0  pyh1a96a4e_0  conda-forge                  
  + fsspec       2022.8.2  pyhd8ed1ab_0  conda-forge/noarch     Cached
  - s3fs         2023.6.0  pyhd8ed1ab_0  conda-forge                  
  + s3fs         2022.8.2  pyhd8ed1ab_0  conda-forge/noarch     Cached
```

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by mdemoret-nv** [comment]
In the near term, we might need to make this note in documentation. Long term, we should switch to using the new RAPIDS CDN to download these files instead of boto3.
