### ISSUE TITLE
[BUG]: UNAVAILABLE: Internal: onnx runtime error 7: Load model from /models/triton-model-repo/log-parsing-onnx/1/model.onnx failed:Protobuf parsing failed.   

### ISSUE THREAD

**Issue by nyck33** [nv-morpheus/Morpheus#1197]
### Version

23.07.02-runtime

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

I just want to run this example: Example cyBERT Morpheus Pipeline for Apache Log Parsing

But keep getting:

```
base) nyck33@nyck33-ubuntu2204:/media/nyck33/StorageSSD/cybersecurity/Morpheus$ docker run --rm -ti --gpus=all -p8000:8000 -p8001:8001 -p8002:8002 -v $PWD/models:/models nvcr.io/nvidia/tritonserver:23.06-py3 tritonserver --model-repository=/models/triton-model-repo --exit-on-error=false --model-control-mode=explicit --load-model log-parsing-onnx

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 23.06 (build 62878575)
Triton Server Version 2.35.0

Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

I0915 12:39:29.184291 1 libtorch.cc:2253] TRITONBACKEND_Initialize: pytorch
I0915 12:39:29.184324 1 libtorch.cc:2263] Triton TRITONBACKEND API version: 1.13
I0915 12:39:29.184331 1 libtorch.cc:2269] 'pytorch' TRITONBACKEND API version: 1.13
I0915 12:39:29.305838 1 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f802e000000' with size 268435456
I0915 12:39:29.306165 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I0915 12:39:29.310915 1 model_lifecycle.cc:462] loading: log-parsing-onnx:1
I0915 12:39:29.311971 1 onnxruntime.cc:2530] TRITONBACKEND_Initialize: onnxruntime
I0915 12:39:29.311983 1 onnxruntime.cc:2540] Triton TRITONBACKEND API version: 1.13
I0915 12:39:29.311988 1 onnxruntime.cc:2546] 'onnxruntime' TRITONBACKEND API version: 1.13
I0915 12:39:29.311993 1 onnxruntime.cc:2576] backend configuration:
{"cmdline":{"auto-complete-config":"true","backend-directory":"/opt/tritonserver/backends","min-compute-capability":"6.000000","default-max-batch-size":"4"}}
I0915 12:39:29.321810 1 onnxruntime.cc:2641] TRITONBACKEND_ModelInitialize: log-parsing-onnx (version 1)
I0915 12:39:29.323132 1 onnxruntime.cc:692] skipping model configuration auto-complete for 'log-parsing-onnx': inputs and outputs already specified
I0915 12:39:29.323509 1 onnxruntime.cc:2702] TRITONBACKEND_ModelInstanceInitialize: log-parsing-onnx (GPU device 0)
I0915 12:39:29.328852 1 onnxruntime.cc:2754] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0915 12:39:29.328869 1 onnxruntime.cc:2682] TRITONBACKEND_ModelFinalize: delete model state
E0915 12:39:29.328881 1 model_lifecycle.cc:626] failed to load 'log-parsing-onnx' version 1: Internal: onnx runtime error 7: Load model from /models/triton-model-repo/log-parsing-onnx/1/model.onnx failed:Protobuf parsing failed.
I0915 12:39:29.328890 1 model_lifecycle.cc:753] failed to load 'log-parsing-onnx'
I0915 12:39:29.328953 1 server.cc:603] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0915 12:39:29.329000 1 server.cc:630] 
+-------------+-----------------------------------------------------------------+------------------------------------------------------------------------+
| Backend     | Path                                                            | Config                                                                 |
+-------------+-----------------------------------------------------------------+------------------------------------------------------------------------+
| pytorch     | /opt/tritonserver/backends/pytorch/libtriton_pytorch.so         | {}                                                                     |
| onnxruntime | /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so | {"cmdline":{"auto-complete-config":"true","backend-directory":"/opt/tr |
|             |                                                                 | itonserver/backends","min-compute-capability":"6.000000","default-max- |
|             |                                                                 | batch-size":"4"}}                                                      |
+-------------+-----------------------------------------------------------------+------------------------------------------------------------------------+

I0915 12:39:29.329041 1 server.cc:673] 
+------------------+---------+---------------------------------------------------------------------------------------------------------------------------+
| Model            | Version | Status                                                                                                                    |
+------------------+---------+---------------------------------------------------------------------------------------------------------------------------+
| log-parsing-onnx | 1       | UNAVAILABLE: Internal: onnx runtime error 7: Load model from /models/triton-model-repo/log-parsing-onnx/1/model.onnx fail |
|                  |         | ed:Protobuf parsing failed.                                                                                               |
+------------------+---------+---------------------------------------------------------------------------------------------------------------------------+

I0915 12:39:29.355165 1 metrics.cc:808] Collecting metrics for GPU 0: NVIDIA GeForce GTX 1650
I0915 12:39:29.355437 1 metrics.cc:701] Collecting CPU metrics
I0915 12:39:29.355615 1 tritonserver.cc:2385] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                               |
| server_version                   | 2.35.0                                                                                                               |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration sys |
|                                  | tem_shared_memory cuda_shared_memory binary_tensor_data parameters statistics trace logging                          |
| model_repository_path[0]         | /models/triton-model-repo                                                                                            |
| model_control_mode               | MODE_EXPLICIT                                                                                                        |
| startup_models_0                 | log-parsing-onnx                                                                                                     |
| strict_model_config              | 0                                                                                                                    |
| rate_limit                       | OFF                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                            |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                             |
| min_supported_compute_capability | 6.0                                                                                                                  |
| strict_readiness                 | 1                                                                                                                    |
| exit_timeout                     | 30                                                                                                                   |
| cache_enabled                    | 0                                                                                                                    |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------+

E0915 12:39:29.355639 1 tritonserver.cc:2394] Invalid argument: load failed for model 'log-parsing-onnx': version 1 is at UNAVAILABLE state: Internal: onnx runtime error 7: Load model from /models/triton-model-repo/log-parsing-onnx/1/model.onnx failed:Protobuf parsing failed.;

I0915 12:39:29.356564 1 grpc_server.cc:2445] Started GRPCInferenceService at 0.0.0.0:8001
I0915 12:39:29.356707 1 http_server.cc:3555] Started HTTPService at 0.0.0.0:8000
I0915 12:39:29.398514 1 http_server.cc:185] Started Metrics Service at 0.0.0.0:8002
W0915 12:39:30.357324 1 metrics.cc:573] Unable to get power limit for GPU 0. Status:Success, value:0.000000
W0915 12:39:31.357703 1 metrics.cc:573] Unable to get power limit for GPU 0. Status:Success, value:0.000000
W0915 12:39:32.359668 1 metrics.cc:573] Unable to get power limit for GPU 0. Status:Success, value:0.000000
```
so tried to check the onnx's integrity with 
```
morpheus) nyck33@nyck33-ubuntu2204:/media/nyck33/StorageSSD/cybersecurity/Morpheus/models/triton-model-repo$ python3
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnx
>>> onnx_model = onnx.load("triton-model-repo/log-parsing-onnx/1/model.onnx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nyck33/miniconda3/envs/morpheus/lib/python3.10/site-packages/onnx/__init__.py", line 169, in load_model
    s = _load_bytes(f)
  File "/home/nyck33/miniconda3/envs/morpheus/lib/python3.10/site-packages/onnx/__init__.py", line 73, in _load_bytes
    with open(typing.cast(str, f), "rb") as readable:
FileNotFoundError: [Errno 2] No such file or directory: 'triton-model-repo/log-parsing-onnx/1/model.onnx'
>>> onnx_model = onnx.load("log-parsing-onnx/1/model.onnx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nyck33/miniconda3/envs/morpheus/lib/python3.10/site-packages/onnx/__init__.py", line 170, in load_model
    model = load_model_from_string(s, format=format)
  File "/home/nyck33/miniconda3/envs/morpheus/lib/python3.10/site-packages/onnx/__init__.py", line 212, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "/home/nyck33/miniconda3/envs/morpheus/lib/python3.10/site-packages/onnx/__init__.py", line 143, in _deserialize
    decoded = typing.cast(Optional[int], proto.ParseFromString(s))
google.protobuf.message.DecodeError: Error parsing message
>>> onnx_model = onnx.load("media/nyck33/StorageSSD/cybersecurity/Morpheus/models/triton-model-repo/log-parsing-onnx/1/model.onnx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nyck33/miniconda3/envs/morpheus/lib/python3.10/site-packages/onnx/__init__.py", line 169, in load_model
    s = _load_bytes(f)
  File "/home/nyck33/miniconda3/envs/morpheus/lib/python3.10/site-packages/onnx/__init__.py", line 73, in _load_bytes
    with open(typing.cast(str, f), "rb") as readable:
FileNotFoundError: [Errno 2] No such file or directory: 'media/nyck33/StorageSSD/cybersecurity/Morpheus/models/triton-model-repo/log-parsing-onnx/1/model.onnx'
>>> onnx_model = onnx.load("/media/nyck33/StorageSSD/cybersecurity/Morpheus/models/triton-model-repo/log-parsing-onnx/1/model.onnx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nyck33/miniconda3/envs/morpheus/lib/python3.10/site-packages/onnx/__init__.py", line 170, in load_model
    model = load_model_from_string(s, format=format)
  File "/home/nyck33/miniconda3/envs/morpheus/lib/python3.10/site-packages/onnx/__init__.py", line 212, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "/home/nyck33/miniconda3/envs/morpheus/lib/python3.10/site-packages/onnx/__init__.py", line 143, in _deserialize
    decoded = typing.cast(Optional[int], proto.ParseFromString(s))
google.protobuf.message.DecodeError: Error parsing message
>>> import onnx
>>> print(onnx.__version__)
1.14.1
>>> import google.protobuf
>>> print(google.protobuf.__version__)
4.24.3
>>> pip install --upgrade onnx
  File "<stdin>", line 1
    pip install --upgrade onnx
        ^^^^^^^
SyntaxError: invalid syntax
>>> pip install --upgrade onnx
  File "<stdin>", line 1
    pip install --upgrade onnx
        ^^^^^^^
SyntaxError: invalid syntax
>>> pip install -U onnx
  File "<stdin>", line 1
    pip install -U onnx
        ^^^^^^^
SyntaxError: invalid syntax

```
But that didn't work either.  

### Minimum reproducible example

```shell
See above, maybe the onnx is getting corrupted when I clone the repo?  Or it's bad to begin with?
```

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 [Paste the error here, it will be hidden by default]

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
Hi @nyck33!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.

**Comment by exactlyallan** [comment]
@nyck33 Is this issue occurring when using WSL2? Or a native Ubuntu installation?

**Comment by nyck33** [comment]
@exactlyallan  actually I got tihs working on Native Ubuntu by first running an morpheus container with the `dev null` appended to the `docker run` command so that it persists, then `exec` into the container, then git clone the Morpheus rrepo to the root of the container, then running the script to get the models and examples, then running a Trition inference server on the host and then running the command listed in the log parsing example.  So it works but this feels a bit convoluted.  It may have occurred on WSL2 but now am solely working on native Ubuntu.

**Comment by nyck33** [comment]
@exactlyallan I maybe should have made a new issue but please take a look here for a different problem I faced: https://github.com/nv-morpheus/Morpheus/issues/1187#issuecomment-1722375151
