### ISSUE TITLE
[BUG]: No module named mrc.core

### ISSUE THREAD

**Issue by nyck33** [nv-morpheus/Morpheus#1198]
### Version

23.11

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

I try to run the log parsing example:
```
(logparsing) coder ➜ /workspaces/Morpheus/examples/log_parsing $ python run.py     --num_threads 1     --input_file ${MORPHEUS_ROOT}/models/datasets/validation-data/log-parsing-validation-data-input.csv     --output_file ./log-parsing-output.jsonlines     --model_vocab_hash_file=${MORPHEUS_ROOT}/morpheus/data/bert-base-cased-hash.txt     --model_vocab_file=${MORPHEUS_ROOT}/models/training-tuning-scripts/sid-models/resources/bert-base-cased-vocab.txt     --model_seq_length=256     --model_name log-parsing-onnx     --model_config_file=${MORPHEUS_ROOT}/models/log-parsing-models/log-parsing-config-20220418.json     --server_url localhost:8001
Traceback (most recent call last):
  File "/workspaces/Morpheus/examples/log_parsing/run.py", line 18, in <module>
    from inference import LogParsingInferenceStage
  File "/workspaces/Morpheus/examples/log_parsing/inference.py", line 23, in <module>
    from mrc.core import operators as ops
ModuleNotFoundError: No module named 'mrc.core'
```

### Minimum reproducible example

```shell
Clone repo, start in VSCode as dev container, then make a new conda environment inside the container (not sure why requirements.txt files or environment.yml files are not provided as there are so many packages) based on this conda list output:

(logparsing) coder ➜ /workspaces/Morpheus/examples/log_parsing $ conda list
# packages in environment at /home/coder/.conda/envs/logparsing:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
appdirs                   1.4.4              pyhd3eb1b0_0    anaconda
blas                      1.0                    openblas    anaconda
brotlipy                  0.7.0           py310h7f8727e_1002    anaconda
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.01.10           h06a4308_0    anaconda
certifi                   2022.12.7       py310h06a4308_0    anaconda
cffi                      1.15.1          py310h5eee18b_3    anaconda
charset-normalizer        2.0.4              pyhd3eb1b0_0    anaconda
click                     8.1.7           unix_pyh707e725_0    conda-forge
cryptography              38.0.4          py310h9ce1e76_0    anaconda
cuda-cudart               12.0.107             h59595ed_6    conda-forge
cuda-cudart_linux-64      12.0.107             h59595ed_6    conda-forge
cuda-nvrtc                12.0.76              h59595ed_1    conda-forge
cuda-nvtx                 12.0.76              hcb278e6_0    conda-forge
cuda-python               12.2.0                   pypi_0    pypi
cuda-version              12.0                 hffde075_2    conda-forge
cupy                      12.2.0          py310hfc31588_1    conda-forge
cython                    3.0.2                    pypi_0    pypi
fastrlock                 0.8.2           py310hc6cd4ac_0    conda-forge
fftw                      3.3.9                h27cfd23_1    anaconda
grpcio                    1.57.0          py310h1b8f574_1    conda-forge
idna                      3.4             py310h06a4308_0    anaconda
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libabseil                 20230802.0      cxx17_h59595ed_3    conda-forge
libblas                   3.9.0           18_linux64_openblas    conda-forge
libcblas                  3.9.0           18_linux64_openblas    conda-forge
libcublas                 12.0.1.189           hcb278e6_2    conda-forge
libcufft                  11.0.0.21            hcb278e6_1    conda-forge
libcurand                 10.3.1.50            hcb278e6_0    conda-forge
libcusolver               11.4.2.57            hcb278e6_1    conda-forge
libcusparse               12.0.0.76            hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_0    conda-forge
libgfortran-ng            13.2.0               h69a702a_0    conda-forge
libgfortran5              13.2.0               ha4646dd_0    conda-forge
libgomp                   13.2.0               h807b86a_0    conda-forge
libgrpc                   1.57.0               ha4d0f93_1    conda-forge
liblapack                 3.9.0           18_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libnvjitlink              12.0.76              hcb278e6_1    conda-forge
libopenblas               0.3.24          pthreads_h413a1c8_0    conda-forge
libprotobuf               4.23.4               hf27288f_6    conda-forge
libsqlite                 3.43.0               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
mrc                       0.3.1              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
numpy                     1.25.2          py310ha4c1d20_0    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
packaging                 23.1                     pypi_0    pypi
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pooch                     1.4.0              pyhd3eb1b0_0    anaconda
protobuf                  3.20.3                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    anaconda
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1           py310h06a4308_0    anaconda
python                    3.10.12         hd12c33a_0_cpython    conda-forge
python-rapidjson          1.11                     pypi_0    pypi
python_abi                3.10                    3_cp310    conda-forge
re2                       2023.03.02           h8c504da_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.28.1          py310h06a4308_0    anaconda
scipy                     1.10.0          py310heeff2f4_0    anaconda
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tritonclient              2.37.0.9383150           pypi_0    pypi
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   1.26.14         py310h06a4308_0    anaconda
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
(logparsing) coder ➜ /workspaces/Morpheus/examples/log_parsing $ 
```
I will attach a conda environment.yml and pip requirements.txt to this issue.

I followed instructions here: https://github.com/nv-morpheus/MRC

Specifically:

```
# If needed, create a new conda environment
conda create --name mrc python=3.10

# Activate the newly created conda environment
conda activate mrc

# Install MRC Python bindings
conda install -c rapidsai -c nvidia -c conda-forge mrc libmrc
```
```


### Relevant log output

see above.

### Full env printout

says, no such file or directory, I even cd'ed to `/scripts` and did `ls`

### Other/Misc.

_No response_

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
Hi @nyck33!
  
  Thanks for submitting this issue - our team has been notified and we'll get back to you as soon as we can!
  In the mean time, feel free to add any relevant information to this issue.
