### ISSUE TITLE
[BUG]: dfencoder import missing from prod DFP example

### ISSUE THREAD

**Issue by pdmack** [nv-morpheus/Morpheus#1407]
### Version

23.11

### Which installation method(s) does this occur on?

Docker, Conda, Source

### Describe the bug.

Last step of production DFP example fails with 'dfencoder' import missing.

### Minimum reproducible example

```shell
python dfp_azure_pipeline.py --train_users none  --start_time "2022-08-30" --input_file="../../../data/dfp/azure-inference-data/*.json"
```

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 [Downloading artifacts: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 20.53it/s]
2023/12/05 18:28:35 WARNING mlflow.pytorch: Stored model version '1.13.1+cu116' does not match installed PyTorch version '2.0.1'
Error trying to get model
Traceback (most recent call last):
  File "/workspace/examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_inference_stage.py", line 101, in on_data
    loaded_model = model_cache.load_model(self._client)
  File "/workspace/examples/digital_fingerprinting/production/morpheus/dfp/utils/model_cache.py", line 109, in load_model
    self._model = mlflow.pytorch.load_model(model_uri=self._model_uri)
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/mlflow/pytorch/__init__.py", line 713, in load_model
    return _load_model(path=torch_model_artifacts_path, **kwargs)
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/mlflow/pytorch/__init__.py", line 628, in _load_model
    return torch.load(model_path, **kwargs)
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'dfencoder'

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by pdmack** [comment]
closing, was due to old mlflow docker volumes from previous test runs
