### ISSUE TITLE
[BUG]: Morpheus does not run with Pandas 2

### ISSUE THREAD

**Issue by cwharris** [nv-morpheus/Morpheus#1509]
### Version

24.03

### Describe the bug.

Morpheus fails to import `cudf_helpers` when running with Pandas 2.

### Minimum reproducible example

Update `dependencies.yaml` with `pandas=2`, and adjust other versions accordingly. Try to build Morpheus. The build will fail during stub generation due to a failure to import `cudf_helpers`.

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

FAILED: morpheus/_lib/llm/__init__.pyi /home/coder/morpheus/build/release/morpheus/_lib/llm/__init__.pyi 
cd /home/coder/morpheus/build/release && /home/coder/.local/share/venvs/rapids/bin/python3.10 -m pybind11_stubgen morpheus._lib.llm --no-setup-py --log-level WARN -o ./ --root-module-suffix ""
WARNING: Logging before InitGoogleLogging() is written to STDERR
E20240211 19:03:08.649855 757993 cudf_util.cpp:50] Could not load cudf_helpers library: TypeError: expected string or bytes-like object

At:
  /home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pandas/util/version/__init__.py(342): __init__
  /home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pandas/compat/pyarrow.py(21): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pandas/compat/__init__.py(27): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pandas/__init__.py(26): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(1184): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(1184): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(1184): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(1184): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap>(1079): _handle_fromlist
  /home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/cudf/_lib/__init__.py(4): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/cudf/utils/_numba.py(16): _get_cc_60_ptx_file
  /home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/cudf/utils/_numba.py(124): _setup_numba
  /home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/cudf/__init__.py(9): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap>(992): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap>(992): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(1184): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(1176): create_module
  <frozen importlib._bootstrap>(571): module_from_spec
  <frozen importlib._bootstrap>(674): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap>(1078): _handle_fromlist
  /home/coder/morpheus/build/release/morpheus/_lib/__init__.py(14): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(688): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <frozen importlib._bootstrap>(1050): _gcd_import
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap>(992): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <frozen importlib._bootstrap>(1050): _gcd_import
  /usr/lib/python3.10/importlib/__init__.py(126): import_module
  /home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pybind11_stubgen/__init__.py(705): __init__
  /home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pybind11_stubgen/__init__.py(940): main
  /home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pybind11_stubgen/__main__.py(4): <module>
  /usr/lib/python3.10/runpy.py(86): _run_code
  /usr/lib/python3.10/runpy.py(196): _run_module_as_main
Traceback (most recent call last):
  File "cudf_helpers.pyx", line 1, in init morpheus._lib.cudf_helpers
  File "/home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/cudf/__init__.py", line 9, in <module>
    _setup_numba()
  File "/home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/cudf/utils/_numba.py", line 124, in _setup_numba
    _get_cc_60_ptx_file()
  File "/home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/cudf/utils/_numba.py", line 16, in _get_cc_60_ptx_file
    from cudf._lib import strings_udf
  File "/home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/cudf/_lib/__init__.py", line 4, in <module>
    from . import (
  File "avro.pyx", line 1, in init cudf._lib.avro
  File "column.pyx", line 1, in init cudf._lib.column
  File "scalar.pyx", line 1, in init cudf._lib.scalar
  File "types.pyx", line 6, in init cudf._lib.types
  File "/home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat import (
  File "/home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pandas/compat/pyarrow.py", line 10, in <module>
    _palv = Version(Version(pa.__version__).base_version)
  File "/home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pandas/util/version/__init__.py", line 342, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pybind11_stubgen/__main__.py", line 4, in <module>
    main()
  File "/home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pybind11_stubgen/__init__.py", line 940, in main
    _module = ModuleStubsGenerator(_module_name)
  File "/home/coder/.local/share/venvs/rapids/lib/python3.10/site-packages/pybind11_stubgen/__init__.py", line 705, in __init__
    self.module = importlib.import_module(module_or_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/coder/morpheus/build/release/morpheus/_lib/__init__.py", line 14, in <module>
    from . import common
ImportError: initialization failed
ninja: build stopped: subcommand failed.

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by cwharris** [comment]
This was due to a broken arrow build.
