### ISSUE TITLE
[BUG]: morpheus main CLI fails with a pyarrow_hotfix/snappy backtrace (24.03 release)

### ISSUE THREAD

**Issue by pdmack** [nv-morpheus/Morpheus#1603]
### Version

24.03

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

Rebuilt the 24.03 image release (after #1600 was already discovered) and now encounter a new error emanating from the morpheus main CLI.

### Minimum reproducible example

```shell
docker run -it --rm nvcr.io/nvidia/morpheus/morpheus:v24.03.00-runtime morpheus
```

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 ```
 Traceback (most recent call last):
  File "/opt/conda/envs/morpheus/bin/morpheus", line 7, in <module>
    from morpheus.cli import run_cli
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/morpheus/__init__.py", line 21, in <module>
    import pyarrow_hotfix
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/pyarrow_hotfix/__init__.py", line 110, in <module>
    install()
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/pyarrow_hotfix/__init__.py", line 34, in install
    import pyarrow as pa
  File "/opt/conda/envs/morpheus/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: /opt/conda/envs/morpheus/lib/python3.10/site-packages/pyarrow/../../.././liborc.so: undefined symbol: _ZN6snappy11RawCompressEPKcmPcPm
```

</pre></details>

### Full env printout

<details><summary>Click here to see environment details</summary><pre>

 [Paste the results of print_env.sh here, it will be hidden by default]

</pre></details>

### Other/Misc.

There appears to some issues with the snappy conda feedstock.

https://github.com/conda-forge/snappy-feedstock/issues/35

Also, it's not clear that morpheus still needs to apply the pyarrow_hotfix.

https://github.com/nv-morpheus/Morpheus/blob/branch-24.03/morpheus/__init__.py#L21

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by pdmack** [comment]
Presumably fixed via RAPIDS dependencies. snappy downgraded in RAPIDS
