### ISSUE TITLE
[BUG]: ABP pcap example broken 

### ISSUE THREAD

**Issue by pdmack** [nv-morpheus/Morpheus#790]
### Version

23.03

### Which installation method(s) does this occur on?

Conda

### Describe the bug.

Fails with `AttributeError: 'Series' object has no attribute 'columns'`

23.03 has cudf 22.10 and it appears maybe there have been refactoring changes to the Series object for pandas alignment.

### Minimum reproducible example

```shell
python run.py --input_file ../data/abp_pcap_dump.jsonlines --output_file ./pcap_out.jsonlines --model_name 'abp-pcap-xgb' --server_url localhost:8001

per the README
```

### Relevant log output

```shell
At:
  /home/pmackinnon/github/morpheus/examples/abp_pcap_detection/abp_pcap_preprocessing.py(88): pre_process_batch
Preprocessing rate[Complete]: 0 messages [00:01, ? messages/E20230324 08:16:09.253531 543079 runner.cpp:189] Runner::await_join - an exception was caught while awaiting on one or more contexts/instances - rethrowinginf/s]
E20230324 08:16:09.253624 543079 instance.cpp:265] segment::Instance - an exception was caught while awaiting on one or more nodes - rethrowing
E20230324 08:16:09.253652 543079 instance.cpp:223] pipeline::Instance - an exception was caught while awaiting on segments - rethrowing
Preprocessing rate[Complete]: 0 messages [00:00, ? messages/s]
Inference rate[Complete]: 0 inf [00:00, ? inf/s]
Exception occurred in pipeline. Rethrowing
Traceback (most recent call last):
  File "/home/pmackinnon/github/morpheus/morpheus/pipeline/pipeline.py", line 327, in join
    await self._mrc_executor.join_async()
  File "/home/pmackinnon/github/morpheus/examples/abp_pcap_detection/abp_pcap_preprocessing.py", line 88, in pre_process_batch
    for col in df.columns:
AttributeError: 'Series' object has no attribute 'columns'
Add classification rate[Complete]: 0 add-class [00:00, ? add-class/s]
Serialize rate[Complete]: 0 ser [00:00, ? ser/s]
Write to file rate[Complete]: 0 to-file [00:00, ? to-file/s]
====Pipeline Complete====
Traceback (most recent call last):
  File "run.py", line 195, in <module>
    run_pipeline()
  File "/opt/miniconda3/envs/morpheus/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/morpheus/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/morpheus/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/morpheus/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "run.py", line 191, in run_pipeline
    pipeline.run()
  File "/home/pmackinnon/github/morpheus/morpheus/pipeline/pipeline.py", line 598, in run
    asyncio.run(self.run_async())
  File "/opt/miniconda3/envs/morpheus/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/miniconda3/envs/morpheus/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/pmackinnon/github/morpheus/morpheus/pipeline/pipeline.py", line 576, in run_async
    await self.join()
  File "/home/pmackinnon/github/morpheus/morpheus/pipeline/pipeline.py", line 327, in join
    await self._mrc_executor.join_async()
  File "/home/pmackinnon/github/morpheus/examples/abp_pcap_detection/abp_pcap_preprocessing.py", line 88, in pre_process_batch
    for col in df.columns:
AttributeError: 'Series' object has no attribute 'columns'
```

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by pdmack** [comment]
Possibly this rapidsai/cudf#10226
