### ISSUE TITLE
[BUG]: Pass-thru example fails on Hopper-series card

### ISSUE THREAD

**Issue by nvawood** [nv-morpheus/Morpheus#827]
### Version

23.03

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

Installing from NGC 23.03 images on an H100-enabled Cloud Native Stack 9.0 system, the example pass-thru stage fails with "cudaErrorInvalidDeviceFunction invalid device function".

### Minimum reproducible example

```shell
$ cd morpheus/examples/developer_guide/1_simple_python_stage
$ python run.py
```

### Relevant log output

```shell
(morpheus) root@sdk-cli-benchmark-helper:~/morpheus/examples/developer_guide/1_simple_python_stage# python run.py
====Registering Pipeline====
====Building Pipeline====
====Building Pipeline Complete!====
Starting! Time: 1680211510.1585636
Progress: 0 messages [00:00, ? messages/s]====Registering Pipeline Complete!====
====Starting Pipeline====
====Pipeline Started====
====Building Segment: linear_segment_0====
Added source: <from-file-0; FileSourceStage(filename=/workspace/examples/data/email_with_addresses.jsonlines, iterative=False, file_type=FileTypes.Auto, repeat=1, filter_null=True)>
  └─> morpheus.MessageMeta
Added source: <from-file-0; FileSourceStage(filename=/workspace/examples/data/email_with_addresses.jsonlines, iterative=False, file_type=FileTypes.Auto, repeat=1, filter_null=True)>
  └─> morpheus.MessageMeta
Added stage: <pass-thru-1; PassThruStage()>
  └─ morpheus.MessageMeta -> morpheus.MessageMeta
Added stage: <monitor-2; MonitorStage(description=Progress, smoothing=0.05, unit=messages, delayed_start=False, determine_count_fn=None, log_level=LogLevels.INFO)>
  └─ morpheus.MessageMeta -> morpheus.MessageMeta
====Building Segment Complete!====
Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20230330-212510.1501!Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20230330-212510.1501!Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20230330-212510.1501!E20230330 21:25:10.558343  1527 context.cpp:124] linear_segment_0/from-file-0; rank: 0; size: 1; tid: 140144811329280: set_exception issued; issuing kill to current runnable. Exception msg: CUDA error encountered at: /workspace/.conda-bld/work/cpp/src/io/utilities/parsing_utils.cu:125: 98 cudaErrorInvalidDeviceFunction invalid device function
Progress[Complete]: 0 messages [00:00, ? messages/s]E20230330 21:25:10.574455  1501 runner.cpp:189] Runner::await_join - an exception was caught while awaiting on one or more contexts/instances - rethrowing
E20230330 21:25:10.574568  1501 instance.cpp:265] segment::Instance - an exception was caught while awaiting on one or more nodes - rethrowing
E20230330 21:25:10.574592  1501 instance.cpp:223] pipeline::Instance - an exception was caught while awaiting on segments - rethrowing
Progress[Complete]: 0 messages [00:00, ? messages/s]
Exception occurred in pipeline. Rethrowing
Traceback (most recent call last):
  File "/opt/conda/envs/morpheus/lib/python3.8/site-packages/morpheus/pipeline/pipeline.py", line 327, in join
    await self._mrc_executor.join_async()
RuntimeError: CUDA error encountered at: /workspace/.conda-bld/work/cpp/src/io/utilities/parsing_utils.cu:125: 98 cudaErrorInvalidDeviceFunction invalid device function
====Pipeline Complete====
Traceback (most recent call last):
  File "run.py", line 55, in <module>
    run_pipeline()
  File "run.py", line 51, in run_pipeline
    pipeline.run()
  File "/opt/conda/envs/morpheus/lib/python3.8/site-packages/morpheus/pipeline/pipeline.py", line 598, in run
    asyncio.run(self.run_async())
  File "/opt/conda/envs/morpheus/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/morpheus/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/conda/envs/morpheus/lib/python3.8/site-packages/morpheus/pipeline/pipeline.py", line 576, in run_async
    await self.join()
  File "/opt/conda/envs/morpheus/lib/python3.8/site-packages/morpheus/pipeline/pipeline.py", line 327, in join
    await self._mrc_executor.join_async()
RuntimeError: CUDA error encountered at: /workspace/.conda-bld/work/cpp/src/io/utilities/parsing_utils.cu:125: 98 cudaErrorInvalidDeviceFunction invalid device function
```

### Full env printout

```shell
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA H100 PCIe    On   | 00000000:03:00.0 Off |                    0 |
| N/A   31C    P0    65W / 350W |   4007MiB / 81559MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by pdmack** [comment]
Pretty sure that this is a cuDF issue based on the error. 22.10 is not compiled for Hopper (sm_90) but that support is in RAPIDS 23.02.

I would expect other RAPIDS dependencies for Morpheus to break on Hopper also:
```
cudf
cuml
dask-cuda
dask-cudf
libcudf
libcuml
libcumlprims
libraft-distance
libraft-headers
libraft-nn
librmm
pylibraft
raft-dask
rmm
```

**Comment by dagardner-nv** [comment]
As mentioned in the Morpheus meeting this morning, adopting 23.02 would also pick up a C++ JSON writer for cudf #761

**Comment by jarmak-nv** [comment]
@nvawood Is still still an issue? Morpheus `23.07` updated its RAPIDS ver to `23.06` so hopefully all should be cleared up, but want your confirm.

Thanks!

**Comment by jarmak-nv** [comment]
@nvawood closing as this should be resolved. If that's not the case, please reopen - thanks!
