### ISSUE TITLE
[BUG]: in the DFP pipeline, dfencoder sometimes fails to train, and when it does the training pipeline errors out. 

### ISSUE THREAD

**Issue by Tzahi-cpacket** [nv-morpheus/Morpheus#858]
### Version

23.01

### Describe the bug.

When training for individual 'username's, it is possible that for a specific user the training will not converge, even though the input data is technically valid.

A robust pipeline will overcome this error, and move on to the next username. maybe marking this username in some way for inference.

What the v23.01 pipeline does however is error out. 

### Relevant log output

```shell
====Registering Pipeline====
====Building Pipeline====
====Building Segment: linear_segment_0====
====Building Segment Complete!====
====Building Pipeline Complete!====
Starting! Time: 1680812454.5476243
====Registering Pipeline Complete!====
====Starting Pipeline====
====Pipeline Started====
Added source: <from-multi-file-0; MultiFileSource(filenames=['/workspace/examples/data/dfp/tcp-open-training-data/GoodBad.JSON'])>
  └─> fsspec.OpenFiles
Added stage: <dfp-file-batcher-1; DFPFileBatcherStage(date_conversion_func=functools.partial(<function date_extractor at 0x7f53f59a6040>, filename_regex=re.compile('(?P<year>\\d{4})-(?P<month>\\d{1,2})-(?P<day>\\d{1,2})T(?P<hour>\\d{1,2})(:|_)(?P<minute>\\d{1,2})(:|_)(?P<second>\\d{1,2})(?P<microsecond>\\.\\d{1,6})?Z')), period=D, sampling_rate_s=0, start_time=None, end_time=None)>
  └─ fsspec.OpenFiles -> List[fsspec.core.OpenFiles]
Added stage: <dfp-s3-to-df-2; DFPFileToDataFrameStage(schema=DataFrameInputSchema(json_columns=[], column_info=[DateTimeColumn(name='timestamp', dtype=<class 'datetime.datetime'>, input_name='timestamp'), RenameColumn(name='username', dtype=<class 'str'>, input_name='username'), ColumnInfo(name='A', dtype=<class 'int'>), ColumnInfo(name='B', dtype=<class 'int'>), ColumnInfo(name='C', dtype=<class 'int'>), ColumnInfo(name='D', dtype=<class 'int'>), ColumnInfo(name='E', dtype=<class 'int'>), ColumnInfo(name='F', dtype=<class 'int'>), ColumnInfo(name='G', dtype=<class 'int'>)], preserve_columns=None, row_filter=None), filter_null=True, file_type=FileTypes.JSON, parser_kwargs={'lines': False, 'orient': 'records'}, cache_dir=/workspace/.cache/dfp)>
  └─ List[fsspec.core.OpenFiles] -> cudf.DataFrame
Added stage: <dfp-split-users-3; DFPSplitUsersStage(include_generic=False, include_individual=True, skip_users=[], only_users=None)>
  └─ cudf.DataFrame -> dfp.DFPMessageMeta
Added stage: <dfp-rolling-window-4; DFPRollingWindowStage(min_history=300, min_increment=300, max_history=60d, cache_dir=/workspace/.cache/dfp)>
  └─ dfp.DFPMessageMeta -> dfp.MultiDFPMessage
Added stage: <dfp-preproc-5; DFPPreprocessingStage(input_schema=DataFrameInputSchema(json_columns=[], column_info=[ColumnInfo(name='timestamp', dtype=<class 'datetime.datetime'>), ColumnInfo(name='username', dtype=<class 'str'>), ColumnInfo(name='A', dtype=<class 'int'>), ColumnInfo(name='B', dtype=<class 'int'>), ColumnInfo(name='C', dtype=<class 'int'>), ColumnInfo(name='D', dtype=<class 'int'>), ColumnInfo(name='E', dtype=<class 'int'>), ColumnInfo(name='F', dtype=<class 'int'>), ColumnInfo(name='G', dtype=<class 'int'>), IncrementColumn(name='logcount', dtype=<class 'int'>, input_name='timestamp', groupby_column='username', period='D')], preserve_columns=re.compile('(_batch_id)'), row_filter=None))>
  └─ dfp.MultiDFPMessage -> dfp.MultiDFPMessage
Added stage: <dfp-training-6; DFPTraining(model_kwargs=None, epochs=30, validation_size=0.1)>
  └─ dfp.MultiDFPMessage -> morpheus.MultiAEMessage
Added stage: <dfp-mlflow-model-writer-7; DFPMLFlowModelWriterStage(model_name_formatter={user_id}, experiment_name_formatter=dfp/tcp-open/training/{reg_model_name}, databricks_permissions=None)>
  └─ morpheus.MultiAEMessage -> morpheus.MultiAEMessage
_download_method is dask
NoneType: None
Creating dask cluster...
Creating dask cluster... Done. Dashboard: http://172.19.0.2:8787/status
dfs details: len(dfs)=1
NoneType: None
dfs details: dfs[0].head(2)=                  timestamp  username      A  B  C  D     E      F  G
0 2022-10-25 23:50:56+00:00  gooduser  21489  0  0  0  1498      3  0
1 2022-10-25 23:50:56+00:00  gooduser    212  1  0  0   234  49152  0
NoneType: None
S3 objects to DF complete. Rows: 1813, Cache: miss, Duration: 1596.8961715698242 ms
Stopping dask cluster...
Batch split users complete. Input: 1813 rows from 2022-10-25 23:50:56+00:00 to 2022-10-25 23:53:52+00:00. Output: 2 users, rows/user min: 583, max: 1230, avg: 906.50. Duration: 5.40 ms
Stopping dask cluster... Done.
Rolling window complete for baduser in 20.33 ms. Input: 583 rows from 2022-10-25 23:50:56+00:00 to 2022-10-25 23:53:52+00:00. Output: 583 rows from 2022-10-25 23:50:56+00:00 to 2022-10-25 23:53:52+00:00
Preprocessed 583 data for logs in 2022-10-25 23:50:56+00:00 to 2022-10-25 23:53:52+00:00 in 23.207426071166992 ms
Rolling window complete for gooduser in 28.53 ms. Input: 1230 rows from 2022-10-25 23:50:56+00:00 to 2022-10-25 23:53:52+00:00. Output: 1230 rows from 2022-10-25 23:50:56+00:00 to 2022-10-25 23:53:52+00:00
Training AE model for user: 'baduser'...
data set details, train_df.shape=(524, 7), validation_df.shape=(59, 7)
Preprocessed 1230 data for logs in 2022-10-25 23:50:56+00:00 to 2022-10-25 23:53:52+00:00 in 22.50814437866211 ms
E20230406 20:21:02.794371  1191 context.cpp:124] linear_segment_0/dfp-training-6; rank: 0; size: 1; tid: 139997252404992: set_exception issued; issuing kill to current runnable. Exception msg: RuntimeError: torch.cat(): expected a non-empty list of Tensors

At:
  /opt/conda/envs/morpheus/lib/python3.8/site-packages/dfencoder/autoencoder.py(1041): get_anomaly_score_losses
  /opt/conda/envs/morpheus/lib/python3.8/site-packages/dfencoder/autoencoder.py(1000): get_anomaly_score_with_losses
  /opt/conda/envs/morpheus/lib/python3.8/site-packages/dfencoder/autoencoder.py(774): fit
  /workspace/examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_training.py(95): on_data
  /workspace/examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_training.py(108): node_fn
E20230406 20:21:02.796510  1114 runner.cpp:189] Runner::await_join - an exception was caught while awaiting on one or more contexts/instances - rethrowing
E20230406 20:21:02.797950  1114 instance.cpp:265] segment::Instance - an exception was caught while awaiting on one or more nodes - rethrowing
E20230406 20:21:02.797995  1114 instance.cpp:223] pipeline::Instance - an exception was caught while awaiting on segments - rethrowing
Exception occurred in pipeline. Rethrowing
Traceback (most recent call last):
  File "/opt/conda/envs/morpheus/lib/python3.8/site-packages/morpheus/pipeline/pipeline.py", line 315, in join
    await self._mrc_executor.join_async()
  File "/workspace/examples/digital_fingerprinting/production/morpheus/dfp/stages/dfp_training.py", line 95, in on_data
    model.fit(train_df, epochs=self._epochs, val=validation_df)
  File "/opt/conda/envs/morpheus/lib/python3.8/site-packages/dfencoder/autoencoder.py", line 774, in fit
    mse_loss, bce_loss, cce_loss, _ = self.get_anomaly_score_with_losses(df_for_loss_stats)
  File "/opt/conda/envs/morpheus/lib/python3.8/site-packages/dfencoder/autoencoder.py", line 1000, in get_anomaly_score_with_losses
    mse, bce, cce = self.get_anomaly_score_losses(df)
  File "/opt/conda/envs/morpheus/lib/python3.8/site-packages/dfencoder/autoencoder.py", line 1037, in get_anomaly_score_losses
    cce_loss_slice = torch.cat(cce_loss_slice_of_each_feat, dim=1) # merge the tensors into one (n_records * n_features) tensor
RuntimeError: torch.cat(): expected a non-empty list of Tensors
====Pipeline Complete====
```

### Full env printout

```shell
(there is not scripts folder in ./external/utilities in my installation, v23.01)
```

### Other/Misc.

I've sent a notbook and data to reproduce this to awood. 

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by jarmak-nv** [comment]
It appears that the fit function in dfencoder encounters an error when no categorical feature is present in the feature set, affecting both `23.01` and `23.03`. Specifically, the `get_anomaly_score_losses` function is responsible for this behavior.

We have identified this as a bug and will schedule a fix for the issue in our next release to add support for use cases where no categorical features are in use.
