### ISSUE TITLE
[BUG]: Remove LD_LIBRARY hack in DFP visualization 

### ISSUE THREAD

**Issue by dagardner-nv** [nv-morpheus/Morpheus#882]
### Version

23.07

### Which installation method(s) does this occur on?

Docker

### Describe the bug.

This was a last-minute fix in [828](https://github.com/nv-morpheus/Morpheus/pull/828) for 23.03

Likely this is due to the fact that nodejs was installed via apt, and instead we should look to installing nodejs via conda, which is what we do for the dev env, but this example is based upon the release container which doesn't contain node. 

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by dagardner-nv** [comment]
cc: @efajardo-nv

**Comment by efajardo-nv** [comment]
@dagardner-nv thanks. i'll add the nodejs conda install to PR #873.

**Comment by efajardo-nv** [comment]
@dagardner-nv using `nodejs` conda install still doesn't fix this error:
```
error - Error: libnvrtc.so.11.2: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1275:18)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at bindings (/workspace/external/morpheus-visualizations/DFP/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/workspace/external/morpheus-visualizations/DFP/node_modules/@rapidsai/cuda/build/js/addon.js:20:25)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32) {
  code: 'ERR_DLOPEN_FAILED'
```

**Comment by dagardner-nv** [comment]
@efajardo-nv Yeah... I tried that as well https://github.com/dagardner-nv/Morpheus/tree/david-dfp-viz

We'll probably need to reach out to the nodejs rapids folks, ask them if they've encountered this before mixing nodejs/yarn packages inside of a conda env.

**Comment by efajardo-nv** [comment]
@dagardner-nv confirmed this is an issue with `node-rapids`. fix is included in latest version which will be published soon.
